Learning Objectives
By completing this assignment, you should be able to:

Use pandas equivalents of dplyr verbs:
filter() → boolean indexing / .loc[]
mutate() → .assign()
group_by() → .groupby()
summarise() → .agg()
arrange() → .sort_values()
Apply boolean logic correctly using & and |
Use method chaining for readable, step-by-step transformations
Create grouped summary tables with multiple statistics
Dataset
Use the provided dataset: housing.csv

import pandas as pd
df = pd.read_csv("housing.csv")

In [5]:
import pandas as pd

In [7]:
df = pd.read_csv("housing.csv")

Part A – Core Wrangling (Method Chaining Required)
Using one chained expression, create a summary table that:

Keeps only observations where price > 250000
Keeps only homes with size > 1000
Creates a new variable:
price_per_sqft = price / size
Groups by neighborhood
Computes:
mean of price_per_sqft
median of price_per_sqft
count of homes
Sorts the result by mean price_per_sqft (descending)
Requirements
Do NOT create intermediate variables (df2, df3, etc.)
Use .assign() to create new variables
Use .agg() with named aggregation
Do not use reset_index() (we did not cover it yet)
Output format note
After groupby(), pandas will put neighborhood in the index. That is OK for this assignment. Your final output can look like a table where neighborhood is on the left as the index.

Deliverable
Paste your code
Show the final DataFrame output

In [9]:
(df
 .loc[(df["price"] > 250000) & (df["size"] > 1000)]
 .assign(price_per_sqft=lambda d: d["price"] / d["size"])
 .groupby("neighborhood")
 .agg(
     mean_price_per_sqft=("price_per_sqft", "mean"),
     median_price_per_sqft=("price_per_sqft", "median"),
     count_homes=("price_per_sqft", "size")
 )
 .sort_values("mean_price_per_sqft", ascending=False)
)

              mean_price_per_sqft  median_price_per_sqft  count_homes
neighborhood
Downtown               977.820905            1001.557049           99
Midtown                921.141446             901.992377           92
Suburb                 861.917078             836.878644          157
Uptown                 860.935608             843.653468           99
Waterfront             849.508891             792.663291           48

Part B – Translation to dplyr
In a Markdown cell, write the equivalent dplyr code that performs the same transformation.

Your R pipeline should include:

filter()
mutate()
group_by()
summarise()
arrange()
Reflection (3–6 sentences)
Answer:

Which syntax feels clearer for you — pandas chaining or dplyr pipelines?
What feels similar between them?
What feels different?

In [12]:
library(dplyr)

housing %>%
  filter(price > 250000, size > 1000) %>%
  mutate(price_per_sqft = price / size) %>%
  group_by(neighborhood) %>%
  summarise(
    mean_price_per_sqft = mean(price_per_sqft),
    median_price_per_sqft = median(price_per_sqft),
    count_homes = n()
  ) %>%
  arrange(desc(mean_price_per_sqft))

SyntaxError: invalid syntax (1067292794.py, line 3)

Since I am more acquanted with python, the syntax of python makes much more sense to me.




The flow between pandas chaining and dplyr pipelines is very similar — 
both move step-by-step through filtering and arranging.




The main difference would be Pandas using .assign(). Pandas need to use python specific syntax.

Part C – Boolean Logic Debugging
The following code produces an error:

df[df["price"] > 250000 & df["size"] > 1000]
Tasks
Fix the code.
Explain why the error occurs.
Rewrite the filter using .query() instead.

In [25]:
## Fixed Code


df[(df["price"] > 250000) & (df["size"] > 1000)]

     listing_id    price         size  bedrooms neighborhood          type
0        100001  1500000  1280.741760       1.0       Suburb     Townhouse
1        100002  1500000  1406.283113       2.0       Uptown  SingleFamily
2        100003  1500000  4146.825713       6.0       Suburb   MultiFamily
3        100004  1500000  3946.599818       6.0       Suburb  SingleFamily
4        100005  1500000  1243.751760       1.0     Downtown   MultiFamily
..          ...      ...          ...       ...          ...           ...
595      100596  1500000  1443.241197       3.0      Midtown         Condo
596      100597  1500000  1083.909714       2.0       Suburb         Condo
597      100598  1500000  1600.126432       1.0       Suburb  SingleFamily
598      100599  1500000  1248.216637       1.0   Waterfront         Condo
599      100600  1500000  1450.981922       NaN       Suburb  SingleFamily

[495 rows x 6 columns]

In [ ]:
## Why the error occurs:

## & has higher precedence than >. Hence Py reads it firstly as 250000 & df["size"].

In [27]:
df.query("price > 250000 and size > 1000")

     listing_id    price         size  bedrooms neighborhood          type
0        100001  1500000  1280.741760       1.0       Suburb     Townhouse
1        100002  1500000  1406.283113       2.0       Uptown  SingleFamily
2        100003  1500000  4146.825713       6.0       Suburb   MultiFamily
3        100004  1500000  3946.599818       6.0       Suburb  SingleFamily
4        100005  1500000  1243.751760       1.0     Downtown   MultiFamily
..          ...      ...          ...       ...          ...           ...
595      100596  1500000  1443.241197       3.0      Midtown         Condo
596      100597  1500000  1083.909714       2.0       Suburb         Condo
597      100598  1500000  1600.126432       1.0       Suburb  SingleFamily
598      100599  1500000  1248.216637       1.0   Waterfront         Condo
599      100600  1500000  1450.981922       NaN       Suburb  SingleFamily

[495 rows x 6 columns]

Part D – Short Concept Questions
Answer briefly (2–4 sentences each):

Why must we wrap each condition in parentheses when using & in pandas?
What is the advantage of method chaining over creating many temporary DataFrames?
In .agg(mean_price=("price", "mean")), what does "price" represent? What does "mean" represent?
When you groupby("neighborhood"), why does neighborhood appear on the left (index) in the result table?

1. We must use parenthesis when using & in pandas else any operator which has higher preference will get precedance than the other operators thereby changing the output of the code.

2. Method chaining keeps transformations in one readable pipeline, making the workflow easier to follow. It reduces clutter from multiple intermediate variables and lowers the risk of accidental overwriting. 
It also mirrors step-by-step data transformation logic more clearly.

3. price represents the column being aggregated. 
mean represents the function which is applied to that column.

4. It is the default nature of the pandas. The grouping identitiy should be at the left side after the groupby().

Optional Extension (Extra practice)
Create a second summary table grouped by type that reports: - mean price - median price - count of listings (Use method chaining again.)

In [41]:
(df
 .groupby("type")
 .agg(
     mean_price=("price", "mean"),
     median_price=("price", "median"),
     count_listings=("price", "size")
 )
 .sort_values("mean_price", ascending=False)
)

              mean_price  median_price  count_listings
type
Condo          1500000.0     1500000.0             183
MultiFamily    1500000.0     1500000.0              63
SingleFamily   1500000.0     1500000.0             235
Townhouse      1500000.0     1500000.0             119